---
- hosts: masters[0]
  become: true
  gather_facts: false
  vars_files:
    - ./vars/cert_vars.yml
    - ./vars/workers.yml
  tasks:
    - name: create CERTs and CSRs folders
      file:
        path: ./{{ item }}
        owner: kuberadm
        group: kuberadm
        state: directory
        mode: '1777'
      tags: create_folders
      with_items:
        - CERTs
        - CSRs

    - name: create private keys for K8s components exept kubelet
      openssl_privatekey:
        path: "./CERTs/{{ item.value.name }}-key.pem"
        size: "{{ item.value.key_size }}"
        type: "{{ item.value.key_type }}"
        backup: yes       
      with_dict: "{{ ssl_cert_csr  }}"
    
    - name: create private keys for kubelet nodes
      openssl_privatekey:
        path: "./CERTs/{{ item }}-key.pem"
        size: "2048"
        type: "RSA"
        backup: yes       
      with_items: "{{ k8s_hosts.workers }}"

    - name: create CSR for K8s components exept kubelet
      openssl_csr:
        path: ./CSRs/{{ item.value.name }}.csr
        privatekey_path: ./CERTs/{{ item.value.name }}-key.pem
        country_name: RU
        organization_name: "{{ item.value.o }}"
        organizational_unit_name: "{{ item.value.ou }}"
        email_address: werton13@testground.net
        common_name: "{{ item.value.cn }}"
      with_dict: "{{ ssl_cert_csr }}"

    - name: create CSR for kubelet nodes
      openssl_csr:
        path: ./CSRs/{{ item }}.csr
        privatekey_path: ./CERTs/{{ item }}-key.pem
        country_name: RU
        organization_name: "system:nodes"
        organizational_unit_name: "Kubernetes The Hard Way"
        email_address: werton13@testground.net
        common_name: "system:node:{{ item }}"
      with_items: "{{ k8s_hosts.workers }}"

    - name: Generate a CA Self Signed OpenSSL certificate
      openssl_certificate:
        path: ./CERTs/ca.pem
        privatekey_path: ./CERTs/ca-key.pem
        csr_path: ./CSRs/ca.csr
        provider: selfsigned
      tags:
       - CACert   
    - name: Generate an CA signed OpenSSL certificates for  K8s components exept kubelet
      openssl_certificate:
        path: ./CERTs/{{ item.value.name }}.pem
        csr_path: ./CSRs/{{ item.value.name }}.csr
        ownca_path: ./CERTs/ca.pem
        ownca_privatekey_path: ./CERTs/ca-key.pem
        provider: ownca
      tags:
       - mgmt-certs 
      with_dict: "{{ ssl_cert_csr }}"
    
    - name: Generate  OpenSSL certificates for K8s kubelet's
      openssl_certificate:
        path: ./CERTs/{{ item }}.pem
        csr_path: ./CSRs/{{ item }}.csr
        ownca_path: ./CERTs/ca.pem
        ownca_privatekey_path: ./CERTs/ca-key.pem
        provider: ownca
      tags:
       - kubelet-certs 
      with_items: "{{ k8s_hosts.workers }}"

#KUBERNETES_PUBLIC_ADDRESS=$(gcloud compute addresses describe kubernetes-the-hard-way \
#  --region $(gcloud config get-value compute/region) \
#  --format 'value(address)')
#
#KUBERNETES_HOSTNAMES=kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local
#
#cat > kubernetes-csr.json <<EOF
#{
#  "CN": "kubernetes",
#  "key": {
#    "algo": "rsa",
#    "size": 2048
#  },
#  "names": [
#    {
#      "C": "US",
#      "L": "Portland",
#      "O": "Kubernetes",
#      "OU": "Kubernetes The Hard Way",
#      "ST": "Oregon"
#    }
#  ]
#}
#EOF
#
#cfssl gencert \
#  -ca=ca.pem \
#  -ca-key=ca-key.pem \
#  -config=ca-config.json \
#  -hostname=10.32.0.1,10.240.0.10,10.240.0.11,10.240.0.12,${KUBERNETES_PUBLIC_ADDRESS},127.0.0.1,${KUBERNETES_HOSTNAMES} \
#  -profile=kubernetes \
#  kubernetes-csr.json | cfssljson -bare kubernetes
#
#}