---
  - hosts: masters[0]
    become: true
    gather_facts: false
    vars_files:
      - ./vars/workers.yml
      - ./vars/cert_vars.yml

     
    tasks:
      - name: Generating the Data Encryption key
        shell: |
          head -c 32 /dev/urandom | base64 
        register: ENCRYPTION_KEY

      - name: Create the encryption-config.yaml encryption config file
        template:
          src: ./templates/encryption-config.yaml.j2
          dest: /home/kuberadm/encryption-config.yaml
          owner: kuberadm
          group: kuberadm
          mode: '0700'
  - hosts: masters[1]
    become: true
    gather_facts: false
    tasks:
      - name: Distribute encryption config file to K8s-masters
        synchronize:
          src:  /home/kuberadm/encryption-config.yaml
          dest: /home/kuberadm/encryption-config.yaml
          rsync_path: "/usr/bin/rsync"
          set_remote_user: true
        tags: copy_encryption_config_file
        delegate_to: "{{ groups.masters | first }}"
