  - hosts: masters[1]
    become: true
    gather_facts: false
    vars_files:
      - ./vars/cert_vars.yml
      - ./vars/workers.yml
    tasks:
      - name: copy kubeconfigs for admin, scheduler, controller-manager to masters

        synchronize:
          src:  /home/kuberadm/{{ item }}.kubeconfig
          dest: /home/kuberadm/{{ item }}.kubeconfig
          rsync_path: "/usr/bin/rsync"
          set_remote_user: true
        tags: copy_control_kubeconfigs
        with_items:
          - "{{ k8s_roles.control }}"
        delegate_to: "{{ groups.masters | first }}"