---
  - hosts: workers[1]
    become: true
    gather_facts: false
    vars_files:
      - ./vars/workers.yml
      - ./vars/cert_vars.yml
    # generate kubeconfig files for the controller manager, kubelet, kube-proxy,
    # and scheduler clients and the admin user.
     
    tasks:
      - name: create kubelet Kubernetes Configuration File for workers
        shell: |
          kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=ca.pem --embed-certs=true \
          --server=https://192.168.32.200:6443 --kubeconfig={{ inventory_hostname }}.kubeconfig
          kubectl config set-credentials system:node:{{ inventory_hostname }} --client-certificate={{ inventory_hostname }}.pem \
          --client-key={{ inventory_hostname }}-key.pem --embed-certs=true --kubeconfig={{ inventory_hostname }}.kubeconfig
          kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:node:{{ inventory_hostname }} \
          --kubeconfig={{ inventory_hostname }}.kubeconfig
          kubectl config use-context default --kubeconfig={{ inventory_hostname }}.kubeconfig
        tags: kubeconfig_kubelet

      - name: create kube-proxy Kubernetes Configuration File
        shell: |
          kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=ca.pem --embed-certs=true \
          --server=https://192.168.32.200:6443 --kubeconfig=kube-proxy.kubeconfig
          kubectl config set-credentials system:kube-proxy  --client-certificate=./CERTs/kube-proxy.pem --client-key=./CERTs/kube-proxy-key.pem \
          --embed-certs=true --kubeconfig=kube-proxy.kubeconfig
          kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:kube-proxy \
          --kubeconfig=kube-proxy.kubeconfig
          kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig
        tags: kubeconfig_kube-proxy 
        delegate_to: "{{ groups.masters | first }}"

      - name: create kube-controller-manager,kube-scheduler,admin user Kubernetes Configuration File's
        shell: |
          kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=ca.pem --embed-certs=true \
          --server=https://127.0.0.1:6443 --kubeconfig={{ item }}.kubeconfig
          kubectl config set-credentials system:{{ item }} --client-certificate=./CERTs/{{ item }}.pem \
          --client-key=./CERTs/{{ item }}-key.pem --embed-certs=true --kubeconfig={{ item }}.kubeconfig
          kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:{{ item }} \
          --kubeconfig={{ item }}.kubeconfig
          kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
        with_items: "{{ k8s_roles.control }}"
        tags: kubeconfig_admin_scheduler_cntr-mgr
        delegate_to: "{{ groups.masters | first }}"

