---
- hosts: workers[1]
  gather_facts: false
  become: yes
  pre_tasks:
    - name: update apt
      apt:
        update_cache: yes
        name: sshpass
        state: present
  tasks:
    - name: create admin user for K8s cluster
      user:
        name: kuberadm
        comment: "K8s cluster admin"
        uid: 1040
        shell: /bin/bash
        groups: adm,cdrom,sudo,dip,plugdev,lxd
        append: yes
        update_password: always
        # mkpasswd --method=SHA-512 --stdin
        password: '$6$rISPAqFv$8/VG8HkO.xD1WEQWYAqZAaqleY.DzttMIAjrPKW3w6lfwWQK6F4oaak.UYubmly8L8Gw8OUgaqjKQXeOSwxct1'
...
