- name: Copy kube-controller-manager and kube-scheduler kubeconfig files to each controller instance
  synchronize:
    src:  "/home/{{ os_admin_username }}/{{ item.value.kube_user_id }}.kubeconfig"
    dest: "/home/{{ os_admin_username }}/{{ item.value.kube_user_id }}.kubeconfig"
    rsync_path: "/usr/bin/rsync"
    set_remote_user: true
  when: (item.key  == "kube_controller_manager") or
      (item.key  == "kube_scheduler")
  loop: "{{ kubeconfigs | dict2items }}"
  delegate_to: "{{ groups.masters | first }}"

