- name: Copy kube-proxy kubeconfig files to each worker instance
  synchronize:
    src:  "/home/{{ os_admin_username }}/{{ kubeconfigs['kube_proxy'].kube_user_id }}.kubeconfig"
    dest: "/home/{{ os_admin_username }}/{{ kubeconfigs['kube_proxy'].kube_user_id }}.kubeconfig"
    rsync_path: "/usr/bin/rsync"
    set_remote_user: true
  delegate_to: "{{ groups.masters | first }}"
