---
  - hosts: workers
    become: true
    gather_facts: false
    vars_files:
      - ../shared_vars/base_vars.yaml
      - ../shared_vars/cert_vars.yaml
    tasks:
      - name: create kubeconfig files for K8s Authentication
        import_tasks: create_kubeconfigs_workers.yaml

  - hosts: masters[0]
    gather_facts: true
    become: true
    vars_files:
      - ../shared_vars/base_vars.yaml
      - ../shared_vars/cert_vars.yaml
    tasks:
      - name: Create kubeconfig files for kube-proxy, kube-controller-manager, kube-scheduler and for admin user
        import_tasks: create_kubeconfigs_control_plane.yaml
    

  - hosts: masters[1] # we have two masters and already created set of files on master[0]
    become: true
    gather_facts: false
    vars_files:
      - ../shared_vars/base_vars.yaml
      - ../shared_vars/cert_vars.yaml
    tasks:
      - name: Copy kube-controller-manager and kube-scheduler kubeconfig files to each controller instance
        import_tasks: distribute_kubeconfigs_masters.yaml
        tags: kubeconfig_masters
    
  - hosts: workers
    become: true
    gather_facts: false
    vars_files:
      - ../shared_vars/base_vars.yaml
      - ../shared_vars/cert_vars.yaml
    tasks:
      - name: Copy  kubelet and kube-proxy kubeconfig files to each worker instance
        import_tasks: distribute_kubeconfigs_workers.yaml
    